# Generated by Django 5.1.3 on 2024-11-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa do veículo', max_length=10)),
                ('numero_documento', models.CharField(help_text='Número da NF ou contêiner', max_length=50)),
                ('peso_entrada', models.DecimalField(blank=True, decimal_places=2, help_text='Peso de entrada (kg)', max_digits=10, null=True)),
                ('data_entrada', models.DateTimeField(blank=True, help_text='Data e hora da entrada', null=True)),
                ('peso_saida', models.DecimalField(blank=True, decimal_places=2, help_text='Peso de saída (kg)', max_digits=10, null=True)),
                ('data_saida', models.DateTimeField(blank=True, help_text='Data e hora da saída', null=True)),
            ],
        ),
    ]
