# Generated by Django 5.1.3 on 2024-11-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropesagem',
            name='imagem_entrada',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_entrada/'),
        ),
        migrations.AddField(
            model_name='registropesagem',
            name='imagem_saida',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_saida/'),
        ),
    ]
