# Generated by Django 5.1.3 on 2024-11-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesagem', '0002_registropesagem_imagem_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropesagem',
            name='imagem_entrada',
            field=models.ImageField(blank=True, help_text='Imagem da entrada', null=True, upload_to='imagens/entrada/'),
        ),
        migrations.AlterField(
            model_name='registropesagem',
            name='imagem_saida',
            field=models.ImageField(blank=True, help_text='Imagem da saída', null=True, upload_to='imagens/saida/'),
        ),
    ]
