version: '3.9'

services:
  app:
    build: .
    container_name: app_django
    volumes:
      - .:/app  # Para refletir alterações locais no container
    ports:
      - "8001:8001"  # A aplicação Django ficará disponível na porta 8000
    environment:
      - TZ=America/Sao_Paulo  # Definir fuso horário
    networks:
      - app_network
    restart: always  # Garantir que o container será reiniciado automaticamente

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Usando o arquivo nginx.conf personalizado
      - ./static:/app/static  # Caso você tenha arquivos estáticos para servir diretamente pelo Nginx
    ports:
      - "8000:80"  # Expondo a porta 80 do Nginx na porta 8000 do host
    depends_on:
      - app  # Garante que o Nginx só será iniciado após o app estar disponível
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
